name: CICD
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote script
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        env:
          ENV_PATH: ${{ secrets.ENV_PATH }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: ENV_PATH
          script: |
            cd $ENV_PATH
            git clone git@github.com:Senedea/portfolionetlify
            cd portfolionetlify
            git checkout master
            git pull           